version: '2'
services:
  web:
    image: httpd
    ports:
      #- "80:8080"
      - "80:8084"
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

